var cloudinary = require("cloudinary").v2;
var gen = require("stability-client");

var ConnectDB = require("../lib/DataBase.js");

// ENV variable for stability API key
var stableAPIKey = process.env.STABLE_API_KEY;

// ENV variable for Cloudinary API key
var cloudName = process.env.CLOUDY_CLOUD_NAME;
var cloudAPI = process.env.CLOUDY_API_KEY;
var cloudSecret = process.env.CLOUDY_API_SECRET;

// Cloudinary storage API config
cloudinary.config({
  cloud_name: cloudName,
  api_key: cloudAPI,
  api_secret: cloudSecret,
});

module.exports = {
  GenerateImage: (text, response, storyObject) => {
    const api = gen.generate({
      prompt: text,
      apiKey: stableAPIKey,
      width: 512,
      height: 512,
    });
    api.on("image", ({ buffer, filePath }) => {
      uploadImage(filePath, storyObject, response);
      console.log("Image", buffer, filePath);
    });
    api.on("end", (data) => {
      console.log("Generating Complete", data);
    });
  },
};

const uploadImage = (filePath, storyObject, response) => {
  cloudinary.uploader
    .upload(filePath, { tags: "gen1" })
    .then(function (image) {
      console.log();
      console.log("** File Upload (Promise)");
      console.log(
        "* public_id for the uploaded image is generated by Cloudinary's service."
      );
      console.log("* " + image.public_id);
      console.log("* " + image.url);

      // Send the image URL back to the client
      response.send(image.url);

      // Add the image and text strings
      ConnectDB.addEntry({
        public_id: image.public_id,
        image_url: image.url,
        storyText: storyObject,
      });
    })
    .catch(function (err) {
      console.log();
      console.log("** File Upload (Promise)");
      if (err) {
        console.warn(err);
      }
    });
};
